blog1/urls.py
from django.urls import path
from . import views

app_name = 'blog1' # URL Reverse에서 namespace 역할을 하게 됨

urlpatterns = [
    path("", views.post_list, name="post_list"),
]

djangoreact/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic import TemplateView, RedirectView

urlpatterns = [
    # path('', TemplateView.as_view(template_name='root.html'), name='root'),
    path('', RedirectView.as_view(
        # url='/instagram/'
        pattern_name='instagram:post_list',
    ), name='root'),
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path("blog1/", include("blog1.urls")),
    path("instagram/", include("instagram.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

instagram/urls.py
from django.urls import path, re_path, register_converter
from . import views
from .converters import YearConverter, MonthConverter, DayConverter

register_converter(YearConverter, 'year')
register_converter(MonthConverter, 'month')
register_converter(DayConverter, 'day')

app_name = 'instagram'  # URL Reverse에서 namespace 역할을 하게 됨

urlpatterns = [
    path('new/', views.post_new, name='post_new'),
    path('<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('<int:pk>/delete/', views.post_delete, name='post_delete'),

    path('', views.post_list, name='post_list'),
    path('<int:pk>/', views.post_detail, name='post_detail'),

    # re_path(r'(?P<pk>\d+)/$', views.post_detail),
    # path('archives/<int:year>/', views.archives_year),
    # re_path(r'archives/(?P<year>20\d{2})/', views.archives_year),
    # path('archives/<yyyy:year>/', views.archives_year),

    path('archive/', views.post_archive, name='post_archive'),
    path('archive/<year:year>/', views.post_archive_year, name='post_archive_year'),
    # path('archive/<year:year>/<month:month>/', views.post_archive_month, name='post_archive_month'),
    # path('archive/<year:year>/<month:month>/<day:day>/', views.post_archive_day, name='post_archive_day'),
]

instagram/models.py
from django.conf import settings
from django.core.validators import MinLengthValidator
from django.db import models
from django.urls import reverse


# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    message = models.TextField(
        validators=[MinLengthValidator(10)]
    )
    photo = models.ImageField(blank=True, upload_to='instagram/psot/%Y/%m%d')
    tag_set = models.ManyToManyField('Tag', blank=True)
    is_public = models.BooleanField(default=False, verbose_name='공개 여부')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Java의 toSting
    def __str__(self):
        # return f"Custom Post object ({self.id})"
        return self.message

    def get_absolute_url(self):
        return reverse('instagram:post_detail', args=[self.pk])

    # 기본 정렬 지정하기
    class Meta:
        ordering = ['-id']

    # def message_length(self):
    #     return len(self.message)
    # message_length.short_description = "메세지 글자수"


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             limit_choices_to={'is_public': True})
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    # post_set = models.ManyToManyField('Post')

    def __str__(self):
        return self.name

instagram/forms.py
import re

from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message', 'photo', 'tag_set', 'is_public']

    def clean_message(self):
        message = self.cleaned_data.get('message')
        if message:
            message = re.sub(r'[a-zA-Z]+', '', message)
        return message

instagram/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpRequest, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, ListView, ArchiveIndexView, YearArchiveView, CreateView, UpdateView, \
    DeleteView
from .models import Post
from .forms import PostForm


# @login_required
# def post_new(request):
#     if request.method == 'POST':
#         form = PostForm(request.POST, request.FILES)
#         if form.is_valid():
#             # post = form.save()
#             post = form.save(commit=False)
#             post.author = request.user  # 현재 로그인 User Insatance
#             post.save()
#             messages.success(request, '포스팅을 저장 했습니다.')
#
#             return redirect(post)
#     else:
#         form = PostForm()
#
#     return render(request, 'instagram/post_form.html', {
#         'form': form,
#         'post': None,
#     })

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        messages.success(self.request, '포스팅을 저장 하였습니다.')
        return super().form_valid(form)


post_new = PostCreateView.as_view()


# @login_required
# def post_edit(request, pk):
#     post = get_object_or_404(Post, pk=pk)
#
#     if post.author != request.user:
#         messages.error(request, '작성자만 수정 가능합니다.')
#         return redirect(post)
#
#     if request.method == 'POST':
#         form = PostForm(request.POST, request.FILES, instance=post)
#         if form.is_valid():
#             post = form.save()
#             messages.success(request, '포스팅을 수정 했습니다.')
#             return redirect(post)
#     else:
#         form = PostForm(instance=post)
#
#     return render(request, 'instagram/post_form.html', {
#         'form': form,
#         'post': post,
#     })

class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        messages.success(self.request, '포스팅을 수정 했습니다.')
        return super().form_valid(form)


post_edit = PostUpdateView.as_view()


# @login_required
# def post_delete(request, pk):
#     post = get_object_or_404(Post, pk=pk)
#     if request.method == 'POST':
#         post.delete()
#         messages.success(request, '포스팅을 삭제 하였습니다.')
#         return redirect('instagram:post_list')
#     return render(request, 'instagram/post_confirm_delete.html', {
#         'post': post,
#     })

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post

    # success_url = reverse('instagram:post_list')
    # success_url = reverse_lazy('instagram:post_list')
    def get_success_url(self):
        return reverse('instagram:post_list')

post_delete = PostDeleteView.as_view()


# post_list = login_required(ListView.as_view(model=Post, paginate_by=10))

# @method_decorator(login_required, name='dispatch')
# class PostListView(ListView):

class PostListView(LoginRequiredMixin, ListView):
    model = Post
    paginate_by = 10


post_list = PostListView.as_view()

# @login_required
# def post_list(request):
#     # request.GET
#     # request.POST
#     # request.FILES
#     qs = Post.objects.all()
#     q = request.GET.get('q', '')
#
#     if q:
#         qs = qs.filter(message__icontains=q)
#
#     # instagram/templates/instagram/post_list.html
#     return render(request, 'instagram/post_list.html', {
#         'post_list': qs,
#         'q': q,
#     })


# def post_detail(request: HttpRequest, pk: int) -> HttpResponse:
#     # try:
#     #     post = Post.objects.get(pk=pk)
#     # except:
#     #     raise Http404
#     post = get_object_or_404(Post, pk=pk)
#
#     return render(request, 'instagram/post_detail.html', {
#         'post': post,
#     })
# post_detail = DetailView.as_view(model=Post)

# post_detail = DetailView.as_view(
#     model=Post,
#     queryset=Post.objects.filter(is_public=True)
# )

class PostDetailView(DetailView):
    model = Post
    # queryset = Post.objects.filter(is_public=True)

    def get_queryset(self):
        qs = super().get_queryset()
        if not self.request.user.is_authenticated:
            qs = qs.filter(is_public=True)

        return qs


post_detail = PostDetailView.as_view()


# def archives_year(request, year):
#     return HttpResponse(f"{year} !!")

post_archive = ArchiveIndexView.as_view(model=Post, date_field='created_at', paginate_by=10)

post_archive_year = YearArchiveView.as_view(model=Post, date_field='created_at', make_object_list=True)

instagram/templates/instagram/layout.html
{% extends "layout.html" %}

instagram/templates/instagram/post_archive.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8"/>
    <title>Instagram / Post Archive</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
    <h2>latest</h2>
    {{ latest }}

    <h2>date_list</h2>
    {% for date in date_list %}
{#        {{ date.year }}#}
        {{ date|date:"Y" }}
    {% endfor %}
</body>
</html>

instagram/templates/instagram/post_archive_year.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8"/>
    <title>Instagram / Post Archive Year</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
    <h2>year</h2>
    {{ year }}
    <h2>previous_year</h2>
    {{ previous_year }}
    <h2>next_year</h2>
    {{ next_year }}
    <h2>object_list</h2>
    {{ object_list }}
</body>
</html>

instagram/templates/instagram/post_confirm_delete.html
{% extends "instagram/layout.html" %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}

        <div class="alert alert-danger">
            정말 삭제하시겠습니까?
        </div>

        <a href="{{ post.get_absolute_url }}" class="btn btn-secondary">
            취소
        </a>

        <input type="submit" value="삭제하겠습니다." class="btn btn-danger"/>
    </form>
{% endblock %}

instagram/templates/instagram/post_detail.html
{% extends "instagram/layout.html" %}
{% load bootstrap4 %}

{% block title %}
    Instagram / Post Detail pk#{{ post.pk }}
{% endblock title %}

{% block content %}
    <h2>Author: {{ post.author }}</h2>

    {% if post.photo %}
        <div>
            <img src="{{ post.photo.url }}" style="width: 100px;"/>
        </div>
    {% endif %}

    {{ post.message|linebreaks }}
    <hr/>
    <a href="{% url 'instagram:post_list' %}" class="btn btn-primary">
        목록
    </a>

    <a href="{% url 'instagram:post_edit' post.pk %}" class="btn btn-info">
        수정
    </a>

    <a href="{% url 'instagram:post_delete' post.pk %}" class="btn btn-danger">
        삭제
    </a>

{% endblock content %}

instagram/templates/instagram/post_form.html
{% extends 'instagram/layout.html' %}
{% load bootstrap4 %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
{#        <table>#}
{#            {{ form }}#}
{#        </table>#}

        {% buttons %}
            <button class="btn btn-primary">
                저장
            </button>
        {% endbuttons %}
{#        <input type="submit" value="저장" />#}
    </form>
    <hr/>
    {% if post %}
        <a href="{{ post.get_absolute_url }}" class="btn btn-secondary">
            내용으로
        </a>
    {% endif %}
    <a href="{% url 'instagram:post_list' %}" class="btn btn-primary">
        목록
    </a>
{% endblock %}

instagram/templates/instagram/post_list.html
{% extends "instagram/layout.html" %}
{% load bootstrap4 %}

{% block title %}
    Instagram / Post List
{% endblock title %}

{% block content %}
    <form action="" method="get">
        <input type="text" name="q" value="{{ q }}"/>
        <input type="submit" value="검색"/>
    </form>

    <a href="{% url 'instagram:post_new' %}" class="btn btn-primary btn-block mt-3 mb-3">
        새 포스팅
    </a>

    <table class="table table-bordered table-hover">
        <tbody>
            {% for post in post_list %}
                <tr>
                    <td>
                        {{ post.pk }}
                    </td>
                    <td>
                        {%  if post.photo %}
                            <img src="{{ post.photo.url }}" style="width: 100px;"/>
                        {% else %}
                            No Photo
                        {% endif %}
                    </td>
                    <td>
{#                        <a href="/instagram/{{ post.pk }}/">#}
{#                        <a href="{% url 'instagram:post_detail' post.pk %}" >#}
                        <a href="{{ post.get_absolute_url }}">
                            {{ post.message }}
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{#    {{ page_obj }}#}
    {% if is_paginated %}
        {% bootstrap_pagination page_obj size="small" justify_content="center"%}
    {% endif %}
{% endblock content %}